In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("Placement_Data_Full_Class.csv")
#dataset.info()

In [3]:
#dir(dataset)
#dataset["gender"].dtype

In [4]:
#dataset.describe()

In [5]:
"""
def univariate(dataset):
    Quan=dataset.select_dtypes(exclude=object)
    Qual=dataset.select_dtypes(include=object)
    return Quan,Qual
"""

'\ndef univariate(dataset):\n    Quan=dataset.select_dtypes(exclude=object)\n    Qual=dataset.select_dtypes(include=object)\n    return Quan,Qual\n'

In [6]:
from UnivariateFile import UnivariateAnalysis as ua

In [7]:
Quan,Qual=ua.univariate(dataset)

In [8]:
descriptive=ua.univariate_descriptive(dataset,Quan)
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1-25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2-50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3-75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,671200.0
Q4-100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,37.0,50.0,50.0,51.21,200000.0
Max,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [9]:
##Identifying the columns with Outliers
lesser_outlier,greater_outlier=ua.Identify_Outliers(descriptive,Quan)
lesser_outlier,greater_outlier

(['hsc_p'], ['hsc_p', 'degree_p', 'salary'])

In [10]:
##Replacing the outliers with Outlier range values
ua.replace_outliers(dataset,descriptive,lesser_outlier,greater_outlier)

/Users/Max/Desktop/AI - Mohana/DataScience/Week 5/Univariate Analysis/1.QuanQual/UnivariateFile.py:54: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]<descriptive[columnname]["Lesser_range"]]=descriptive[columnname]["Lesser_range"]
/Users/Max/Desktop/AI - Mohana/DataScience/Week 5/Univariate Analysis/1.QuanQual/UnivariateFile.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/DataScience/Week 5/Univariate Analysis/1.QuanQual/UnivariateFile.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]
/Users/Max/Desktop/AI - Mohana/DataScience/Week 5/Univariate Analysis/1.QuanQual/UnivariateFile.py:56: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset[columnname][dataset[columnname]>descriptive[columnname]["Greater_range"]]=descriptive[columnname]["Greater_range"]

In [11]:
##Validating the replacements by executing the descriptive table values and Outliers list

for columnname in Quan:
    descriptive[columnname]["Mean"]=dataset[columnname].mean()
    descriptive[columnname]["Median"]=dataset[columnname].median()
    descriptive[columnname]["Mode"]=dataset[columnname].mode()[0]
    descriptive[columnname]["Q1-25%"]=dataset.describe()[columnname]["25%"]
    descriptive[columnname]["Q2-50%"]=dataset.describe()[columnname]["50%"]
    descriptive[columnname]["Q3-75%"]=dataset.describe()[columnname]["75%"]
    descriptive[columnname]["99%"]=np.nanpercentile(dataset[columnname], 99)
    descriptive[columnname]["Q4-100%"]=dataset.describe()[columnname]["max"]
    descriptive[columnname]["IQR"]=descriptive[columnname]["Q3-75%"]-descriptive[columnname]["Q1-25%"]
    descriptive[columnname]["1.5rule"]=1.5*descriptive[columnname]["IQR"]
    descriptive[columnname]["Lesser_range"]=descriptive[columnname]["Q1-25%"]-descriptive[columnname]["1.5rule"]
    descriptive[columnname]["Greater_range"]=descriptive[columnname]["Q3-75%"]+descriptive[columnname]["1.5rule"]
    descriptive[columnname]["Min"]=dataset[columnname].min()
    descriptive[columnname]["Max"]=dataset[columnname].max()
    
    
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.334744,66.358558,72.100558,62.278186,277648.648649
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1-25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2-50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3-75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.129,83.86,97.0,76.1142,390000.0
Q4-100%,215.0,89.4,91.15,88.5,98.0,77.89,390000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Lesser_range,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
Greater_range,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Min,1,40.89,42.75,50.0,50.0,51.21,200000.0
Max,215,89.4,91.15,88.5,98.0,77.89,390000.0

In [12]:
##Validating whether the columns with Outliers are replaced, by making sure that the lists are empty

lesser_outlier=[]
greater_outlier=[]

for columnname in Quan:
    if descriptive[columnname]["Min"]<descriptive[columnname]["Lesser_range"]:
        lesser_outlier.append(columnname)
        
    if descriptive[columnname]["Max"]>descriptive[columnname]["Greater_range"]:
        greater_outlier.append(columnname)
        
print (lesser_outlier)
print (greater_outlier)

[]
[]

In [ ]:
""""dataset["ssc_p"].value_counts()
dataset["ssc_p"].value_counts().values
dataset["ssc_p"].value_counts().sort_index
dataset["ssc_p"].value_counts().sort_values
dataset["ssc_p"].value_counts().index""""""

In [13]:
## Frequency, Relative_frequency, cummulative relative frequency##
from UnivariateFile import UnivariateAnalysis as ua
freqtable=ua.freqtable(dataset,"ssc_p")

In [14]:
ua.freqtable(dataset,"salary")

    Uniq_values  Frequency  Rel_Frequency  Cum_Frequency
0      300000.0         22       0.213592       0.213592
1      250000.0         18       0.174757       0.388350
2      240000.0         15       0.145631       0.533981
3      390000.0         15       0.145631       0.679612
4      260000.0          7       0.067961       0.747573
5      200000.0          6       0.058252       0.805825
6      265000.0          6       0.058252       0.864078
7      360000.0          6       0.058252       0.922330
8      220000.0          5       0.048544       0.970874
9      275000.0          5       0.048544       1.019417
10     210000.0          4       0.038835       1.058252
11     270000.0          4       0.038835       1.097087
12     216000.0          3       0.029126       1.126214
13     350000.0          3       0.029126       1.155340
14     204000.0          2       0.019417       1.174757
15     230000.0          2       0.019417       1.194175
16     276000.0          2       0.019417       1.213592
17     218000.0          2       0.019417       1.233010
18     280000.0          2       0.019417       1.252427
19     252000.0          2       0.019417       1.271845
20     236000.0          2       0.019417       1.291262
21     278000.0          1       0.009709       1.300971
22     233000.0          1       0.009709       1.310680
23     268000.0          1       0.009709       1.320388
24     225000.0          1       0.009709       1.330097
25     380000.0          1       0.009709       1.339806
26     290000.0          1       0.009709       1.349515
27     320000.0          1       0.009709       1.359223
28     255000.0          1       0.009709       1.368932
29     285000.0          1       0.009709       1.378641
30     295000.0          1       0.009709       1.388350
31     340000.0          1       0.009709       1.398058
32     336000.0          1       0.009709       1.407767
33     287000.0          1       0.009709       1.417476
34     264000.0          1       0.009709       1.427184
35     231000.0          1       0.009709       1.436893