In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("Placement_Data_Full_Class.csv")
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 215 entries, 0 to 214
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   sl_no           215 non-null    int64
 1   gender          215 non-null    object
 2   ssc_p           215 non-null    float64
 3   ssc_b           215 non-null    object
 4   hsc_p           215 non-null    float64
 5   hsc_b           215 non-null    object
 6   hsc_s           215 non-null    object
 7   degree_p        215 non-null    float64
 8   degree_t        215 non-null    object
 9   workex          215 non-null    object
 10  etest_p         215 non-null    float64
 11  specialisation  215 non-null    object
 12  mba_p           215 non-null    float64
 13  status          215 non-null    object
 14  salary          148 non-null    float64
dtypes: float64(6), int64(1), object(8)
memory usage: 25.3+ KB

In [3]:
dir(dataset)
dataset["gender"].dtype

dtype('O')

In [4]:
"""
def univariate(dataset):
    Quan=dataset.select_dtypes(exclude=object)
    Qual=dataset.select_dtypes(include=object)
    return Quan,Qual
"""

'\ndef univariate(dataset):\n    Quan=dataset.select_dtypes(exclude=object)\n    Qual=dataset.select_dtypes(include=object)\n    return Quan,Qual\n'

In [5]:
from UnivariateFile import UnivariateAnalysis as ua

In [6]:
Quan,Qual=ua.univariate(dataset)

In [7]:
print(Quan)

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

In [8]:
print(Qual)

['gender', 'ssc_b', 'hsc_b', 'hsc_s', 'degree_t', 'workex', 'specialisation', 'status']

In [12]:
descriptive=pd.DataFrame(index=["Mean","Median","Mode"],columns=Quan)
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [18]:
for columnname in Quan:
    descriptive[columnname]["Mean"]=dataset[columnname].mean()
    descriptive[columnname]["Median"]=dataset[columnname].median()
    descriptive[columnname]["Mode"]=dataset[columnname].mode()[0]
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0